# -*- coding: utf-8 -*-
"""Part_C_Python_Payment_Reconciliation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ktkFnr5OHunRYXmd0xQtF1BKo6hW6W2
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

ledger_df = pd.read_csv("ledger.csv")
gateway_df = pd.read_csv("gateway_export.csv")

print("Ledger rows:", len(ledger_df))
print("Gateway rows:", len(gateway_df))

print("\nLedger columns:")
print(ledger_df.columns.tolist())

print("\nGateway columns:")
print(gateway_df.columns.tolist())

def reconcile_payments(ledger_df, gateway_df):
    # Make copies so the original DataFrames are not changed
    ledger = ledger_df.copy()
    gateway = gateway_df.copy()

    # Make sure transaction IDs are comparable
    ledger_ids = set(ledger["transaction_id"])
    gateway_ids = set(gateway["transaction_id"])

    # 1. Transactions present in ledger but missing from gateway
    missing_in_gateway_ids = ledger_ids - gateway_ids

    missing_in_gateway = ledger[
        ledger["transaction_id"].isin(missing_in_gateway_ids)
    ].copy()

    # 2. Transactions present in gateway but missing from ledger
    missing_in_ledger_ids = gateway_ids - ledger_ids

    missing_in_ledger = gateway[
        gateway["transaction_id"].isin(missing_in_ledger_ids)
    ].copy()

    # 3 & 4. Compare matching transactions using merge
    matched = pd.merge(
        ledger,
        gateway,
        on="transaction_id",
        how="inner",
        suffixes=("_ledger", "_gateway")
    )

    # 3. Amount mismatches
    matched["amount_difference"] = (
        matched["amount_inr_ledger"] -
        matched["amount_inr_gateway"]
    )

    amount_mismatches = matched[
        matched["amount_difference"] != 0
    ].copy()

    # 4. Status mismatches
    status_mismatches = matched[
        matched["status_ledger"] != matched["status_gateway"]
    ].copy()

    return (
        missing_in_gateway,
        missing_in_ledger,
        amount_mismatches,
        status_mismatches
    )

missing_in_gateway, missing_in_ledger, amount_mismatches, status_mismatches = reconcile_payments(
    ledger_df,
    gateway_df
)

print("Transactions missing in gateway:", len(missing_in_gateway))
print("Transactions missing in ledger:", len(missing_in_ledger))
print("Amount mismatches:", len(amount_mismatches))
print("Status mismatches:", len(status_mismatches))

print("=== TRANSACTIONS MISSING IN GATEWAY ===")
display(missing_in_gateway)

print("=== TRANSACTIONS MISSING IN LEDGER ===")
display(missing_in_ledger)

print("=== AMOUNT MISMATCHES ===")
display(
    amount_mismatches[
        [
            "transaction_id",
            "amount_inr_ledger",
            "amount_inr_gateway",
            "amount_difference"
        ]
    ]
)

print("=== STATUS MISMATCHES ===")
display(
    status_mismatches[
        [
            "transaction_id",
            "status_ledger",
            "status_gateway"
        ]
    ]
)

print("=" * 50)
print("        PART C - RECONCILIATION VALIDATION")
print("=" * 50)

print(f"Ledger rows: {len(ledger_df)}")
print(f"Gateway rows: {len(gateway_df)}")

print("\n--- DISCREPANCY COUNTS ---")
print(f"Missing in gateway : {len(missing_in_gateway)}")
print(f"Missing in ledger  : {len(missing_in_ledger)}")
print(f"Amount mismatches  : {len(amount_mismatches)}")
print(f"Status mismatches  : {len(status_mismatches)}")

print("\n--- FUNCTION VALIDATION ---")

assert len(missing_in_gateway) == 27
assert len(missing_in_ledger) == 10
assert len(amount_mismatches) == 16
assert len(status_mismatches) == 9

print("PASS: All four discrepancy outputs generated successfully.")
print("PASS: Amount differences were computed.")
print("PASS: Status differences were identified.")
print("PASS: Part C reconciliation completed.")

print("\n" + "=" * 50)
print("          PART C VALIDATION COMPLETE")
print("=" * 50)